### ISSUE TITLE
#15: How to count the number of objects in JSON

### ISSUE THREAD

**Issue by wenwangcode** [WendyMunmunWang/vegan-kitchen-api#17]
In RecipeResourceTest class, how to count the number of objects from JSON format? 
http://stackoverflow.com/questions/30991925/how-to-find-the-number-of-response-object-in-json

I tried this but it doesn't work.. please help meeeeeeeee :dancer: Thanks!

**Comment by ctkou** [comment]
fixed in branch ticket-5-fixing-post-and-get-recipe
